from . import _geomflow
from ._preprocess import preprocess, ArrayLike
from ._vector_field import CNFVectorField

__all__ = [
    "preprocess",
    "ArrayLike",
    "CNFVectorField",
    "TangentVector2D",
    "TangentVector3D",
    "CotangentVector2D",
    "CotangentVector3D",
    "EuclideanMetric2D",
    "EuclideanMetric3D",
    "ParametrizedVectorField2D",
    "ParametrizedVectorField3D",
    "FlowResult2D",
    "FlowResult3D",
    "FlowIntegrator2D",
    "FlowIntegrator3D",
    "AdjointState2D",
    "AdjointState3D",
    "AdjointSolver2D",
    "AdjointSolver3D",
    "ScalarField2D",
    "ScalarField3D",
    "Divergence2D",
    "Divergence3D",
    "Gradient2D",
    "Gradient3D",
    "CovariantDerivative2D",
    "CovariantDerivative3D",
]

for name in [
    "TangentVector2D",
    "TangentVector3D",
    "CotangentVector2D",
    "CotangentVector3D",
    "EuclideanMetric2D",
    "EuclideanMetric3D",
    "ParametrizedVectorField2D",
    "ParametrizedVectorField3D",
    "FlowResult2D",
    "FlowResult3D",
    "FlowIntegrator2D",
    "FlowIntegrator3D",
    "AdjointState2D",
    "AdjointState3D",
    "AdjointSolver2D",
    "AdjointSolver3D",
    "ScalarField2D",
    "ScalarField3D",
    "Divergence2D",
    "Divergence3D",
    "Gradient2D",
    "Gradient3D",
    "CovariantDerivative2D",
    "CovariantDerivative3D",
]:
    globals()[name] = getattr(_geomflow, name)